const fs = require('fs');
let code = fs.readFileSync('server.ts', 'utf8');

const replacements = [
  [/mport/g, 'import'],
  [/vte/g, 'vite'],
  [/gena/g, 'genai'],
  [/cheero/g, 'cheerio'],
  [/Frestore/g, 'Firestore'],
  [/frestore/g, 'firestore'],
  [/Servce/g, 'Service'],
  [/Emal/g, 'Email'],
  [/emal/g, 'email'],
  [/confg/g, 'config'],
  [/lmt/g, 'limit'],
  [/Authorzaton/g, 'Authorization'],
  [/Orgn/g, 'Origin'],
  [/orgn/g, 'origin'],
  [/Polcy/g, 'Policy'],
  [/tme/g, 'time'],
  [/strng/g, 'string'],
  [/ndex/g, 'index'],
  [/ths/g, 'this'],
  [/wthout/g, 'without'],
  [/wth/g, 'with'],
  [/sesson/g, 'session'],
  [/Sesson/g, 'Session'],
  [/fles/g, 'files'],
  [/fle/g, 'file'],
  [/lsten/g, 'listen'],
  [/lst/g, 'list'],
  [/ma/g, 'mai'],
  [/ncludng/g, 'including'],
  [/nclude/g, 'include'],
  [/fnd/g, 'find'],
  [/fn/g, 'fin'],
  [/tems/g, 'items'],
  [/tem/g, 'item'],
  [/nd/g, 'ind'],
  [/v/g, 'vi'],
  [/actvty/g, 'activity'],
  [/actve/g, 'active'],
  [/val/g, 'valid'],
  [/provde/g, 'provide'],
  [/provder/g, 'provider'],
  [/\bf \(/g, 'if ('],
  [/\bn \b/g, 'in '],
  [/\bt \b/g, 'it '],
  [/\bs \b/g, 'is '],
  [/\bd\b/g, 'id'],
  [/vd/g, 'vid'],
  [/Fnd/g, 'Find'],
  [/Settngs/g, 'Settings'],
  [/settngs/g, 'settings'],
  [/drect/g, 'direct'],
  [/drectly/g, 'directly'],
  [/lke/g, 'like'],
  [/slce/g, 'slice'],
  [/Splce/g, 'Splice'],
  [/splce/g, 'splice'],
  [/f/g, 'if'], // wait NO! That will replace all f's.
];

// Let's refine.
